language: ruby
rvm:
  - 2.0.0
env:
  - DB=sqlite
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:schema:load
  - RAILS_ENV=test bundle exec rake db:seed
  - RAILS_ENV=test bundle exec rake db:test:prepare
before_script:
  - psql -c 'create database myapp_test' -U postgres