development:
  year: 2015
  max_users_limit: 2000
  tutorial_registration_open: false
  lightning_registration_open: false
  program_released: true
  speakers_released: true
  early_bird_ends: 2015-02-09 23:59:59 +1

test:
  year: 2015
  max_users_limit: 2000
  tutorial_registration_open: true
  lightning_registration_open: false
  program_released: true
  early_bird_ends: 2015-02-09 23:59:59 +1

staging:
  year: 2015
  max_users_limit: 2000
  tutorial_registration_open: false
  lightning_registration_open: false
  program_released: true
  speakers_released: true
  early_bird_ends: 2015-02-09 23:59:59 +1

production:
  year: 2015
  max_users_limit: 300
  tutorial_registration_open: false
  lightning_registration_open: false
  program_released: true
  speakers_released: true
  early_bird_ends: 2015-02-09 23:59:59 +1
