development:
  year: 2015
  max_users_limit: 2000
  tutorial_registration_open: false
  lightning_registration_open: false
  program_released: false
  speakers_released: false
  early_bird_ends: 2015-01-24 23:59:59
  opening_keynote: 312
  closing_keynote: 314

test:
  year: 2015
  max_users_limit: 2000
  tutorial_registration_open: true
  lightning_registration_open: false
  program_released: false
  early_bird_ends: 2015-01-24 23:59:59

staging:
  year: 2015
  max_users_limit: 2000
  tutorial_registration_open: false
  lightning_registration_open: false
  program_released: false
  speakers_released: false
  early_bird_ends: 2015-01-24 23:59:59
  opening_keynote: 194
  closing_keynote: 196

production:
  year: 2015
  max_users_limit: 224
  tutorial_registration_open: false
  lightning_registration_open: false
  program_released: false
  speakers_released: false
  early_bird_ends: 2015-01-24 23:59:59
  opening_keynote: 312
  closing_keynote: 314