development:
  year: 2014
  max_users_limit: 2000
  tutorial_registration_open: true
  lightning_registration_open: true
  program_released: true
  early_bird_ends: 2014-01-24 23:59:59
  opening_keynote: 312
  closing_keynote: 314
  wednesday_ws: '256,222,270,220,203,315,316,317'
  thursday_ws1: '318,249,319,321,261,269,200,322'
  thursday_ws2: '320'
  friday_ws1: '323,324,233,279,224,207'
  friday_ws2: ''
  friday_ws3: '251,274,219'

test:
  year: 2014
  max_users_limit: 2000
  tutorial_registration_open: true
  lightning_registration_open: false
  program_released: false
  early_bird_ends: 2014-01-24 23:59:59

staging:
  year: 2014
  max_users_limit: 2000
  tutorial_registration_open: false
  lightning_registration_open: true
  program_released: true
  early_bird_ends: 2014-01-24 23:59:59
  opening_keynote: 312
  closing_keynote: 314
  wednesday_ws: '256,222,270,220,203,315,316,317'
  thursday_ws1: '318,249,319,321,261,269,200,322'
  thursday_ws2: '320'
  friday_ws1: '323,324,233,279,224,207'
  friday_ws2: ''
  friday_ws3: '251,274,219'

production:
  year: 2014
  max_users_limit: 250
  tutorial_registration_open: false
  lightning_registration_open: false
  program_released: true
  early_bird_ends: 2014-01-24 23:59:59
  opening_keynote: 312
  closing_keynote: 314
  wednesday_ws: '256,222,270,220,203,315,316,317'
  thursday_ws1: '318,249,319,321,261,269,200,322'
  thursday_ws2: '320'
  friday_ws1: '323,324,233,279,224,207'
  friday_ws2: ''
  friday_ws3: '251,274,219'