theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: none
theme_advanced_buttons1:
  - bold
  - italic
  - underline
  - strikethrough
  - separator
  - bullist
  - numlist
  - separator
  - outdent
  - indent
  - separator
  - undo
  - redo
  - separator
  - link
  - unlink
  - separator
  - fullscreen
theme_advanced_buttons2:
theme_advanced_buttons3:
plugins:
  - fullscreen
  - paste
paste_auto_cleanup_on_paste: true
paste_remove_styles: true
paste_remove_styles_if_webkit: true
paste_strip_class_attributes: all
paste_retain_style_properties: none
paste_text_sticky: true
paste_text_sticky_default: true
content_css: "/assets/tinymce-custom-content.css"